### ISSUE TITLE
Webpack support

### ISSUE THREAD

**Issue by F21** [glebmachine/postcss-easysprites#10]
This plugin has some really great ideas!

I am interested in using this with webpack. I have already configured the postcss loader for webpack and added the plugin to postcss.

Unfortunately though, I don't think it works with webpack yet, as any compilation I do results in nothing happening.

I would love to see webpack support, because I can then use webpack's fileloaders to load the images and have this plugin deal with spriting.

**Comment by glebmachine** [comment]
Hi, i'm learn to use webpack proper way right now.
In near future i will test this plugin with webpack.

Btw, you can set `imagePaths` and `cssPath` in options.

## Plugin options
 - `imagePath` path for resolve absolute images
 - `spritePath` path for write completed sprites
 - `stylesheetPath` path for resolve relative images (overriding options, css file folder used for default)

Let me know, if it work or if not)

**Comment by F21** [comment]
I got it to work! It must have been a problem with my webpack config earlier today.

I have created a very simple project showing how to use webpack + post-css + postcss-easysprites together: https://github.com/F21/webpack-postcss-easysprites

Maybe we can turn that into a PR and provide a sample webpack project for your plugin?

**Comment by glebmachine** [comment]
Sounds good)

**Comment by F21** [comment]
I've just discovered a tiny flaw when using it with webpack.

The plugin will generate a `sprites.png` file (because I named my spritesheet as `sprites`) in the project root, which is somewhat annoying.

**Comment by tclift** [comment]
@F21 `spritePath` should control the output directory. That file seems to be unused though, because a second `[hash].png` sprite file is generated in the `imagePath`.

Here's how I'm using it with Webpack (using variables rather than this level of nesting, but the example is simpler without the variables):
```TypeScript
import * as ExtractTextPlugin from 'extract-text-webpack-plugin';

const PostcssPluginEasysprites = require('postcss-easysprites');

module: {
  rules: [
    {
      test: /\.pcss$/,
      use: ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: [
          {
            loader: 'postcss-loader',
            options: {
              plugins: () => [
                new PostcssPluginEasysprites({
                  imagePath: './src/main/web',
                  spritePath: './src/main/web/img/sprites',
                }),
              ],
            },
          },
        ],
      }),
    },
    {
      test: /\.png$/,
      loader: 'file',
    },
  ]
}
```

@glebmachine I think this issue can be closed. I'm successfully using the config above with Webpack.
