### ISSUE TITLE
Sprite Layout

### ISSUE THREAD

**Issue by DreadyCrig** [glebmachine/postcss-easysprites#12]
Is there a way to set the generated sprites to use a layout like Top Down or Left to Right?

**Comment by glebmachine** [comment]
Nope, sorry(

Plugin idea is to have sprite easily, with no complicated mechanism.
Try to use this https://github.com/2createStudio/postcss-sprites

**Comment by glebmachine** [comment]
But, you can pass some `options` to `spritesmith` here:
https://github.com/glebmachine/postcss-easysprites/blob/master/index.js#L261

All `spritesmith` options are described here: https://github.com/Ensighten/spritesmith#algorithms

Fill free to fork and patch this plugin.

**Comment by DreadyCrig** [comment]
I like the way yours easily allows you to tag what images are included in what sprites.  

I modified the javascript code to pass the option to spritesmith for this application
