### ISSUE TITLE
background image rule, the last semicolon is not necessary

### ISSUE THREAD

**Issue by jonas8** [glebmachine/postcss-easysprites#138]
On [L452](https://github.com/glebmachine/postcss-easysprites/blob/master/index.js#L452), the regex
```javascript
/background[^:]*.*url[^;]+;/gi.test(rule);
```
should be
```javascript
/background[^:]*.*url[^;]+/gi.test(rule);
```
the last semicolon is not necessary, the css can be like
```css
div{background-image:url(pathto/image.png)}
```
When it work with webpack UglifyJsPlugin, the last semicolon will be remove, if the last rule is background-image, this plugin will not work.

**Comment by glebmachine** [comment]
@jonas8 Thank you!)
Could you please submit PR?

Cheers! 🍺

**Comment by tclift** [comment]
@glebmachine This issue can be closed.
