### ISSUE TITLE
Background repeat is removed by easysprites when it is needed

### ISSUE THREAD

**Issue by jamesfiltness** [glebmachine/postcss-easysprites#14]
I've noticed that if I specify a background-repeat property with a value of no-repeat that it is removed by easysprites in the generated css. Why is this? I can see in the source that it is being removed on line 173 (index.js) along with a comment - " our plugin will insert them when they are necessary." 

Could an option be added to allow background-repeat to be specified and not removed?

**Comment by glebmachine** [comment]
Sprite is a big image with all images in grid. You can't use it for repeated images, sorry)

Keep this image in base64 instead
