### ISSUE TITLE
Support for PostCSS 6.0+?

### ISSUE THREAD

**Issue by xiongwei9** [glebmachine/postcss-easysprites#179]
I want to know how to support for PostCSS 6.0+?
When I use _"postcss-easysprites": "^0.1.8"_ and _"postcss-loader": "^2.0.6"_ at the same time. I get an error:

> Unknown error from PostCSS plugin. Your current PostCSS version is 6.0.9, but postcss-easysprites uses 5.0.10. Perhaps this is th
e source of the error below.

and

> ERROR in ./src/index/index.scss
Module build failed: ModuleBuildError: Module build failed: TypeError: Cannot read property 'insertAfter' of undefined
    at F:\Programmer\webpack\webpack-demo\node_modules\postcss-easysprites\index.js:400:15

But There is no problem when I use  _"postcss-easysprites": "^0.1.7"_ and _"postcss-loader": "^1.2.1"_ 
Could you tell me what to do with it? Thanks.

**Comment by svapreddy** [comment]
I am facing the same issue. The code at Line number 400 in index.js 

`rule.insertAfter(backgroundImage, backgroundPosition);` causing this issue. @glebmachine

**Comment by glebmachine** [comment]
@svapreddy @xiongwei9 , guys, i'm stop using postcss at all(

I will appreciate if you would like to migrate this plugin to postcss 6.0 and publish PR

**Comment by tclift** [comment]
@glebmachine This issue can be closed (same as #180, fixed in #181, released in `0.1.9`).
