### ISSUE TITLE
TypeError: Cannot read property 'insertAfter' of undefined

### ISSUE THREAD

**Issue by svapreddy** [glebmachine/postcss-easysprites#180]
I am using this plugin along other plugins like precss, css-next etc..

        const plugins = [precss({
                path: parsed.dir/*, resolve: function(filename) {}*/
            }), cssnext, postcssUtilities, postcss_console, svgo(), autocorrect, willChange, willChangeFallBack,
            sprites({
                stylesheetPath: parsed.dir,
                imagePath: path.join(parsed.dir, 'images'),
                spritePath: path.join(dest, 'images')
            }),
            // cssnano()
        ];

But in the console I see below errors and messages

    Node#before is deprecated. Use Node#raws.before
    [13:24:51] Easysprites: /Users/reddyp/Documents/GitHub/Betsy/dist/images/elements.png generated.
    [13:24:51] Easysprites: /Users/reddyp/Documents/GitHub/Betsy/dist/images/elements@3x.png generated.
    [13:24:51] Easysprites: /Users/reddyp/Documents/GitHub/Betsy/dist/images/elements@2x.png generated.
    Unknown error from PostCSS plugin. Your current PostCSS version is 6.0.13, but postcss-easysprites uses 5.0.10. Perhaps this is the source of the error below.
    (node:43877) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'insertAfter' of undefined

I debugged the code of this plugin, found that 

    rule.insertAfter(backgroundImage, backgroundPosition); causing this issue.

Can you please let me know what can I do to fix this? If you do not have enough time, please give me some directions, I will make changes and raise a PR.

**Comment by glebmachine** [comment]
Waiting forward your PR, thank you!)
