### ISSUE TITLE
Help better CSS approach

### ISSUE THREAD

**Issue by arianjinx** [glebmachine/postcss-easysprites#46]
Hello this is a wonderful plugin.
I want to ask what's the best way for us to use plugin on hover state? (really curious)
Considering with chrome issue 😢  to avoid flickering for non visible element at first loading.
http://programming.mvergel.com/2012/11/chrome-reloads-sprite-image-on-css.html

Thank you

**Comment by glebmachine** [comment]
If you add the same sprite name to hover image it will do the trick.

But, if you wondering to use transition in background-image property to make your hover effect smooth and soft, this trick wouldn't work.

Transition image should be stored to standalone file. In this case: remove hash from hover image and add before element with single css property: background image pointing to hover image.

This trick will warm hover image up right after Dom element appear on the screen.

Gleb Mikheev

+7 916 118 2821

**Comment by arianraptor** [comment]
Thanks for your response @glebmachine, yes I already did that trick the problem is it's like the browser reloading the image for hovering state as we know that it's already loaded in normal state right?

Anyway is there any working demo with your explanation in 'add before element with single css property: background image pointing to hover image'? :smiley:

**Comment by glebmachine** [comment]
Sure, here you go: @arianraptor 

Example with one single image:
http://codepen.io/anon/pen/OXwoxv

Example with few images and transition between them:
http://codepen.io/anon/pen/EypZbj

**Comment by arianraptor** [comment]
Example number 1 is perfect hehehe, is there any trick to merge background image definition for both hover and normal state? this plugin need to redefine background-image rule right.

Big thanks for example number 2 mate :+1:

**Comment by glebmachine** [comment]
You are welcome!

No, this plugin have no options to merge definition.
Example #1 - is fully supported by this plugin. postcss-easesprites generate same css.

**Comment by patrickcate** [comment]
@arianjinx is this still an issue? I'm only able to reproduce this in Chrome if I have the browser caching turned off (for instance, when the dev tools are open.)

**Comment by arianjinx** [comment]
Hi @patrickcate it's already 3 years ago mate 😆 I lost the context already, you can close this issue if you want to.

Thanks
