### ISSUE TITLE
Refactroing

### ISSUE THREAD

**Issue by glebmachine** [glebmachine/postcss-easysprites#8]
Should get rid of promise hell.
Code must be clear and clean, damn, so f*cking bad legacy code

**Comment by c01nd01r** [comment]
Hi!
When run the task with Gulp, console output:
```"Container#eachRule is deprecated. Use Container#walkRules instead."```
```Container#eachComment is deprecated. Use Container#walkComments instead.```

**Comment by glebmachine** [comment]
Hi)
Yep, now it have some deprecation notifications.
Will fixed in a while. Thank you)

**Comment by shkarupa-alex** [comment]
+1
