### ISSUE TITLE
Various warnings and errors thrown

### ISSUE THREAD

**Issue by tanc** [glebmachine/postcss-easysprites#9]
Hi there,

In my attempts to use this through gulp with gulp-postcss I'm getting the following warnings and errors thrown:

```
Container#eachRule is deprecated. Use Container#walkRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Container#eachComment is deprecated. Use Container#walkComments instead.
Node#before is deprecated. Use Node#raws.before
Comment#left was deprecated. Use Comment#raws.left
Comment#right was deprecated. Use Comment#raws.right
Node#removeSelf is deprecated. Use Node#remove.
URI malformed
Error: URI malformed
```

Everything works fine if postcss-easysprites is removed from the gulp file so I know its this that is throwing the errors. Any ideas?

**Comment by glebmachine** [comment]
Hi!
Notifications is all about deprecations (will fix soon)

URI: malformed - please, provide repro.
What URI cause this error?

**Comment by tanc** [comment]
Thanks for getting back to me.

I have just one url that I'm trying this on and takes the form:

background-image: url(../images/iai-logo-footer.png#sprite);

It would appear to be walking the tree up a level that it doesn't like as when I change the url to remove the ../ I get a different error (file not found) but no URI malformed error.

**Comment by tanc** [comment]
Some more info:

`background-image: url(/images/iai-logo-footer.png#sprite);`
result:
`Easysprites: /path/to/webroot/images/images/iai-logo-footer.png file unreachable or not exists`

`background-image: url(/iai-logo-footer.png#sprite);`
result:
`Error: URI malformed`

So it looks like it is able to find the file but is choking on it for some reason.

**Comment by glebmachine** [comment]
Please, show me your config data.

**Comment by tanc** [comment]
Config is simply:

```
easysprite({
    imagePath:'./images',
    spritePath: './images/sprites'
})
```

I've been able to successfully compile sprites for other files just now. It seems to be the file name of the png, I'll try changing the name and report back.

**Comment by tanc** [comment]
ok, it appears to be an issue with one particular PNG (happened to be the first one I tried!). I don't think its the filename as when I changed the hyphens to underscores and also removed them it still threw the error.

**Comment by glebmachine** [comment]
I think you have psd/jpg/whatever with png extension. 

It's common mistake with Photoshop on mac.
Photoshop on mac don't check file extension on save. 
So, you can insensibly save jpg as png. 

Check your file first

**Comment by tanc** [comment]
I'm pretty sure its something like that. I just requested the designer re-export the file and this time they are all compiling nicely into a sprite sheet. Fantastic! I'm a happy developer now :-)

**Comment by glebmachine** [comment]
You are welcome, i would love to help you again)
